= Commons Logging JBoss Logging

This project implements https://commons.apache.org/proper/commons-logging/[Apache Commons Logging] redirecting logging
to use https://github.com/jboss-logging/jboss-logging[jboss-logging].

== Usage

=== Maven
[source,xml]
----
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>jboss-commons-logging-jboss-logging</artifactId>
    <version>${version.org.jboss.commons-logging-jboss-logging}</version>
</dependency>
----

== Contributing

See the link:CONTRIBUTING.adoc[contributing guide].

== Releasing

Releasing the project requires permission to deploy to Maven Central see https://central.sonatype.org/publish/requirements/[Maven Central Release Requirements].
Once everything is setup, you simply need to run the `./release.sh` script. There are two required parameters:

1. `-r` or `--release` which is the version you want to release
2. `-d` or `--development` which is the next development version.

By default, the release version cannot contain `SNAPSHOT` and the development version, must contain `SNAPSHOT`.

[source,bash]
.Example Command
----
./release.sh -r 1.0.0.Final -d 1.0.1.Final-SNAPSHOT
----

=== Supported Arguments

|===
|Argument | Requires Value | Description

| `-d`, `--development`
| Yes
| The next version for the development cycle.

| `-f`, `--force`
| No
| Forces to allow a SNAPSHOT suffix in release version and not require one for the development version.

| `-h`, `--help`
| N/A
| Displays this help

| `--notes-start-tag`
| Unused
| Passes the `--notes-from-tag` and the argument to the `gh create release` command.

| `-p`, `--prerelease`
| Unused
| Passes the `--prerelease` to the `gh create release` command.

| `-r`, `--release`
| Yes
| The version to be released. Also used for the tag.

| `--dry-run`
| No
| Executes the release in as a dry-run. Nothing will be updated or pushed.

| `-v`, `--verbose`
| No
| Prints verbose output.

|===


Any additional arguments are considered arguments for the Maven command.
